package com.splitscreen.inputbridge

import android.view.InputEvent

/**
 * AIDL-equivalent interface for the Shizuku privileged user service.
 *
 * In a real build, this would be defined in an .aidl file and generated by the
 * Android build system. Here it is expressed as a Kotlin abstract class extending
 * android.os.Binder for direct use without AIDL code generation.
 *
 * The actual AIDL file (IShizukuUserService.aidl) should be placed at:
 *   app/src/main/aidl/com/splitscreen/inputbridge/IShizukuUserService.aidl
 * with the content shown in the companion AIDL file.
 */
abstract class IShizukuUserService : android.os.Binder() {

    companion object {
        abstract class Stub : IShizukuUserService() {
            abstract fun onCreate()
            abstract fun destroy()
            abstract fun injectInputEvent(event: InputEvent?, mode: Int): Boolean
            abstract fun execShell(command: String?): String
        }
    }
}
